website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from website.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from website .models import User
from flask_login import login_user, login_required, logout_user, current_user



auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        identifier = request.form.get('identifier')
        password = request.form.get('password')

        user = User.query.filter((User.email== identifier) |(User.user_name == identifier)).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email/Username does not exist.', category='error')
    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        user_name = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter(User.email == email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(user_name) < 1:
            flash('Username is required.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, user_name=user_name, password=generate_password_hash(
                password1, method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('auth.login'))  # Redirect to the login page

    return render_template("sign_up.html", user=current_user)


website/views.py
from flask import Blueprint, current_app, redirect, render_template, request, flash, jsonify, send_file, url_for
from flask_login import login_required, current_user
from .models import Note, Recording, User
from sqlalchemy.sql import func
from . import db
import json
import pyaudio
import wave
import os


views = Blueprint('views', __name__)

# ------------Profile--------------#

@views.route('/profile')
@login_required
def profile():
    return render_template('profile.html', user=current_user)

from werkzeug.security import generate_password_hash, check_password_hash

@views.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    if request.method == 'POST':
        # Check if a new password is provided
        new_password = request.form.get('password')
        if new_password:
            # Check if the provided current password matches the stored hash
            current_password = request.form['current_password']
            if check_password_hash(current_user.password, current_password):

                current_user.email = request.form['email']
                current_user.user_name = request.form['username']

                # If the current password is correct, proceed with changing the password
                hashed_new_password = generate_password_hash(new_password, method='pbkdf2:sha256')
                # Update the user's password in the database
                current_user.password = hashed_new_password
                # flash('Updated successfully!', 'success')
            else:
                # If the current password is incorrect, show an error message
                flash('Incorrect current password. Update failed!.', 'error')

        db.session.commit()
        flash('Profile updated successfully!', 'success')
        return redirect(url_for('views.profile'))

    return render_template('edit_profile.html', user=current_user)



# ------------Pages--------------#

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == "POST":
        note_text = request.form.get("note")
        if len(note_text) > 0:
            new_note = Note(data=note_text, user=current_user)
            db.session.add(new_note)
            db.session.commit()
    return render_template("home.html", user=current_user)


# ------------Note--------------#

from datetime import datetime

@views.route('/note', methods=['GET', 'POST'])
@login_required
def note():
    if request.method == 'POST':
        note_text = request.form.get('note')
        if len(note_text) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note_text, user_id=current_user.id, date=datetime.now())
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')
    return render_template('Notes.html', user=current_user)



@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    note_id = note['noteId']
    note = Note.query.get(note_id)
    if note and note.user_id == current_user.id:
        db.session.delete(note)
        db.session.commit()
    return jsonify({})

@views.route('/delete-notes', methods=['POST'])
def delete_notes():
    note = json.loads(request.data)
    note_id = note['noteId']
    note = Note.query.get(note_id)
    if note and note.user_id == current_user.id:
        db.session.delete(note)
        db.session.commit()
    return jsonify({})


#---updating note from the Note page  -----


@views.route('/update-note/<int:note_id>', methods=['POST'])
@login_required
def update_note(note_id):
    if request.method == 'POST':
        note_text = request.form.get('update-note')

        existing_note = Note.query.get(note_id)

        if existing_note and existing_note.user_id == current_user.id:
            existing_note.data = note_text
            existing_note.date = func.now()

            db.session.commit()
            flash('Note updated!', category='success')
        else:
            flash('Note not found or you do not have permission!', category='error')

    return redirect(url_for('views.note'))



#--- updating from the home page -----


@views.route('/update-notes/<int:note_id>', methods=['POST'])
@login_required
def update_notes(note_id):
    if request.method == 'POST':
        note_text = request.form.get('update-notes')

        existing_note = Note.query.get(note_id)

        if existing_note and existing_note.user_id == current_user.id:
            existing_note.data = note_text
            existing_note.date = func.now()

            db.session.commit()
            flash('Note updated!', category='success')
        else:
            flash('Note not found or you do not have permission!', category='error')

    return redirect(url_for('views.home'))




#---------Voice-----------#

@views.route('/voice', methods=['POST', 'GET'])
@login_required
def voice():
    user_recordings = Recording.query.filter_by(user_id=current_user.id).all()
    return render_template('Voice.html', user=current_user, recordings=user_recordings)
    

UPLOAD_FOLDER = 'uploads'

def get_next_filename(user_id):
    i = 1
    while os.path.exists(os.path.join(current_app.config['UPLOAD_FOLDER'], f'user_{user_id}_Note_{i}.wav')):
        i += 1
    return f'user_{user_id}_Note_{i}.wav'

@views.route('/record', methods=['POST'])
def record():
    try:
        p = pyaudio.PyAudio()
        stream = p.open(format=pyaudio.paInt16,
                        channels=1,
                        rate=44100,
                        input=True,
                        frames_per_buffer=1024)
        frames = []

        for i in range(0, int(44100 / 1024 * 5)):
            data = stream.read(1024)
            frames.append(data)

        stream.stop_stream()
        stream.close()
        p.terminate()

        user_id = current_user.id if current_user.is_authenticated else None
        filename = get_next_filename(user_id)
        filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)

        wf = wave.open(filepath, 'wb')
        wf.setnchannels(1)
        wf.setsampwidth(pyaudio.PyAudio().get_sample_size(pyaudio.paInt16))
        wf.setframerate(44100)
        wf.writeframes(b''.join(frames))
        wf.close()

  #      Save the recording information to the database
        recording = Recording(user_id=user_id, filename=filename)
        db.session.add(recording)
        db.session.commit()

        return jsonify({'message': 'Recording complete', 'filename': filename},render_template(url_for('views.voice')))
    except Exception as e:
        print(f"Error recording: {e}")
        return jsonify({'error': 'Error recording'}), 500

from datetime import datetime
import pytz

@views.route('/play/<filename>')
@login_required
def play():
    try:
        user_id = current_user.id
        # path = os.path.join(current_app.config['UPLOAD_FOLDER'], f'user_{user_id}_{filename}')
        path = os.path.join(current_app.config['UPLOAD_FOLDER'], get_next_filename(user_id))

        return send_file(path, as_attachment=True)
    except FileNotFoundError:
        return jsonify({'error': 'File not found'}), 404
    except Exception as e:
        return jsonify({'error': f'Error: {e}'}), 500


# @views.route('/play/<filename>')
# @login_required
# def play():
#     data = json.loads(request.data)
#     recording_id= data['recordingId']
#     recording = Recording.query.get(recording_id)
#     if recording and recording.user_id == current_user.id:
#         file_path = os.path.join(current_app.config['UPLOAD_FORDER'], recording.filename)
#         return (file_path)

# --- deleting Voice Note------
    
@views.route('/delete-voice', methods=['POST'])
def delete_voice():
    data = json.loads(request.data)
    recording_id = data['recordingId']
    recording = Recording.query.get(recording_id)
    
    if recording and recording.user_id == current_user.id:
        # Delete the associated audio file
        file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], recording.filename)
        if os.path.exists(file_path):
            os.remove(file_path)
        # Delete the database entry
        db.session.delete(recording)
        db.session.commit()

        return jsonify({'message': 'Recording deleted successfully'})
    else:
        return jsonify({'error': 'Unable to delete recording'}), 400


website/templates/Notes.html
{% extends "base.html" %}{% block title %}Notes{% endblock %} {% block content%}

<div align="center" class="container">
  <form method="POST" class="forming-style" id="noteForm">
    <textarea
      name="note"
      id="note"
      class="text"
      placeholder="Write note here"
    ></textarea>
    <br />
    <div class="palettet">
      <button type="submit" class="btn">Add Note</button>
    </div>
  </form>
</div>
<br />
<br />
<section class="Note-frame">
  <div align="center">
    <ul class="list-group" id="note" style="display: flex; flex-wrap: wrap;">
      {% for note in user.notes %}
      <li
        class="list-group-item Note-list"
        id="list-group-item-{{ note.id }}"
        style="list-style-type: none; width: 20%;" 
      >
        <div style="text-align:left;;">
          <button
            type="button"
            class="close"
            onClick="DeleteNote({{ note.id }})"
            style="background: none; border: none; padding-right: 10px; "
          >
            <i
              class="material-icons"
              style="
                color: black;
                margin: 0;
                text-align: left;
                position: top-left;
              "
            >delete</i>
          </button>
          <button
            type="button"
            class="update"
            onclick="UpdateNote({{ note.id }})"
            style="background: transparent; border: none; padding-right: 10px;"
          >
            <i
              id="rotateButton"
              class="material-icons"
              style="
                color: black;
                margin: 0;
                text-align: left;
                position: top-left;
              "
            >update</i>
          </button>
        </div>
        <form
          method="POST"
          action="{{ url_for('views.update_note', note_id=note.id) }}"
          id="updateNoteForm-{{ note.id }}"
        >
          <textarea
            name="update-note"
            class="text"
            cols="30"
            rows="10"
            style="
              box-sizing: border-box;
              height: fit-content;
              background: transparent;
              border: transparent;
            "
          >{{ note.data }}
        </textarea>
        </form>
      </li>
      {% endfor %}
    </ul>
  </div>
</section>
{% block javascript %}





{% endblock %}
{% endblock %}



<!-- 
<button
type="button"
style="background: transparent; border: none; background-color: {{ note.color }}"
id="changeColorButton-{{ note.id }}"
class="theme-color"
onclick="changeThemeColor({{ note.id }})"
>
<i class="material-icons" style="box-sizing: border-box">palette</i>
</button> -->

website/templates/Voice.html
{% extends "base.html" %} 
{% block title %}Voice Recorder{% endblock %} 
{% block head %}
  <h1 style="text-align: center; margin: 0; padding-top: 2px;">
    <i class="material-icons" style="padding: 10px;">record_voice_over</i>Speak to Remember
    <i class="material-icons" style="padding: 10px; transform: scaleX(-1);">record_voice_over</i>
  </h1>
{% endblock %}
{% block content %}
  <div class="forms-style">
    <p id="recording-time" style="text-align:center; font-weight: bolder; font-size: 40px;">00:00</p>
    <button id="start-recording" style="background: none; border: none; padding-right: 10px;">
      <i class="material-icons" style=" font-size: 40px;">fiber_manual_record</i>
    </button>
    <button id="stop-recording" disabled style="background: none; border: none; padding-right: 10px">
      <i class="material-icons" style=" font-size: 40px;">pause_circle_filled</i>
    </button>
  </div>

  <!-- Add this to your Voice.html file -->
  <h2 align="center">Voice Notes</h2>

  <ul style="display: flex; list-style-type: none;">
    {% for recording in recordings %}
      <li>
        <p>Note: {{ recording.date}}
          <button onclick="deleteRecording({{ recording.id }})" style="background: none; border: none; padding-right: 10px">
            <i class="material-icons">delete</i>
          </button>
        </p>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,  initial-scale=1.0"> 
    <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">
    <!-- <script type="text/javascript" src="{{ url_for('views.voice', filename='record.js') }}"></script> -->
    <script src="{{ url_for('static', filename='record.js') }}"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <style>

      </style>
    <!-- Include the free version of Font Awesome -->
    <!-- google icon library -->
    <!-- https://www.w3schools.com/icons/google_icons_action.asp -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>Home</title>
</head>
<body>
    <nav>
        <ul style="padding: 0; margin: 0;">
            <li style="list-style-type: none; margin: 0; padding: 0;">
                <div class="wrapper">
                    <input type="checkbox" id="btn">
                    <label for="btn" class="menu-btn">
                        <i class="material-icons"></i>
                    </label>
                    <nav id="sidebar">
                        <div class="title">Main Menu</div>
                        {% if user.is_authenticated %}
                        <ul class="list-items">    
                            <li><a href="/" id="home"><i class="material-icons" style="margin-right: 20px;">home</i>Home</a></li>
                            <li><a href="/note" id="voiceNote" ><i class="material-icons" style="margin-right: 20px;">description</i>Note</a></li>
                            <li><a href="/voice" id="voiceNote" ><i class="material-icons" style="margin-right: 20px;">settings_voice</i>Voice Note</a></li>
                            
                            <li><a href="/profile" id="profile"><i class="material-icons" style="margin-right: 20px;">account_circle</i>Profile</a></li>
                            <li><a href="/logout" id="logout"><i class="material-icons" style="margin-right: 20px;">input</i>Logout</a></li> 
                        </ul>
                        {% else %}
                        <ul class="list-items">
                            <li><a href="/login" id="login"><i class="material-icons" style="margin-right: 20px;"></i>Login</a></li>
                            <li><a href="/sign-up" id="signUP"><i class="material-icons" style="margin-right: 20px;"></i>Sign Up</a></li>
                        </ul>
                        {% endif %}
                    </nav>
                </div>
            </li>
            <li class="mystyle">{% block head %}<h1 style="text-align: center; margin: 0; padding-top: 2px;">Write to Remembe</h1>{% endblock %}</li>
        </ul>
    </nav>
   
    <main class="content">
    
        {% block content %} {% endblock %}
    </main>

    <footer>

    </footer>

</body>
</html>

website/templates/edit_profile.html
{% extends "base.html" %} 
{% block title %}Update Profile{% endblock %} 
{% block content%}
    <form action="{{ url_for('views.edit_profile') }}" method="POST" class="forms-style">
        <h2>Edit Profile</h2><br>
        <input type="text" id="username" name="username" value="{{ current_user.user_name }}" required placeholder="Username" >
        <br><br>
        <input type="email" id="email" name="email" value="{{ current_user.email }}" required placeholder="Email" >
        <br><br>
        <div class="password-container">
            <input type="password" id="current_password" name="current_password" placeholder="Current Password" >
            <i class="fas fa-eye" id="togglesPassword"></i><br>
            <input type="password" id="password" name="password" placeholder="New Password" >
            <i class="fas fa-eye" id="togglePassword"></i>
        </div>
        <br><br>
        <button type="submit" class="btn btn-primary" value="Save Changes">Save</button>
    </form>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<br />
<br />
<div class="body" style=""></div>
<head>
  <h1 align="center">All Notes</h1></head
><br /><br /><br />
<section class="Note-frame">
  <div align="center">
    <!-- <h1>Notes</h1> -->
    <!-- <label for="list-group-item" style="font-weight: bolder; position: fixed; text-align: center;"><h1>Notes</h1></label> -->
    <ul class="list-group" id="notes" style="display: flex">
      {% for note in user.notes %}
      <li
        class="list-group-item Note-list"
        id="list-group-item-{{ note.id }}"
        style="list-style-type: none; width: 20%"
      >
        <div style="text-align: left">
          <button
            type="button"
            class="close"
            onClick="DeleteNotes({{ note.id }})"
            style="background: none; border: none; padding-right: 10px"
          >
            <i
              class="material-icons"
              style="
                color: black;
                margin: 0;
                text-align: left;
                position: top-left;
              "
              >delete</i
            >
          </button>
          <button
            type="button"
            class="update"
            onclick="UpdateNotes({{ note.id }})"
            style="background: transparent; border: none; padding-right: 10px"
          >
            <i
              id="rotateButton"
              class="material-icons"
              style="
                color: black;
                margin: 0;
                text-align: left;
                position: top-left;
              "
              >update</i
            >
          </button>
        </div>
        <form
          method="POST"
          action="{{ url_for('views.update_note', note_id=note.id) }}"
          id="updateNoteForm-{{ note.id }}"
        >
          <textarea
            name="update-notes"
            class="text"
            cols="30"
            rows="10"
            style="
              box-sizing: border-box;
              height: fit-content;
              background: transparent;
              border: transparent;
            "
          >
{{ note.data }}
          </textarea>
        </form>
      </li>
      {% endfor %}
    </ul>
  </div>
</section>

{% block javascript %} {% endblock %} {% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
{% block content%}


<div align="center" >
    <form method="POST" class="form-style">
        <h2>Login</h2>
        <input type="text" id="identifier" name="identifier" placeholder="email or Username">
        <br><br>
        <input type="password" id="password" name="password" placeholder="Password">
        <br/><br>
        <button type="submit" class="btn">Login</button>
        <p class="login-signUp">Click to<a href="{{ url_for('auth.sign_up') }}"> Sign Up</a></p>
    </form>
</div>

{% endblock %}

website/templates/profile.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
{% block content%}
    <div class="forms-style" align="center" >
        <div align="left">
            <h2>Profile: </h2><br>
            <p><strong>Username:</strong> {{ current_user.user_name }}</p><br>
            <p><strong>Email:</strong> {{ current_user.email }}</p><br><br>
        </div>
        <!-- <p><strong>password:</strong> {{ current_user.password }}</p> -->
       <a href="{{ url_for('views.edit_profile') }}"> <button type="submit" class="btn" >Edit Profile</button></a>
        
    </div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
{% block content%}
    <div align="center" >
        <form method="POST"  class="form-style">
            <h2>Create Accout</h2>
            <br>
            <div class="form-group">
                <input type="text" id="username" name="username" placeholder="Username">
            </div>
            <br/>
            <div class="form-group">
                <input type="email" id="email" name="email" placeholder="Email Address">
            </div>
            <br />
            <div class="form-group">
                <input type="password" id="password1" name="password1" placeholder="Password">
            </div>
            <br />
            <div class="form-group">
                <input type="password" id="password2" name="password2" placeholder="Confirm Password">
            </div>
            <br/>
            <button type="submit" class="btn">Sing Up</button>
            <p class="login-signUp">Click to<a href="{{ url_for('auth.login') }}"> Login</a></p>
        </form>
    </div>
{% endblock %}